syntax = "proto3";
option csharp_namespace = "ms_user_management.Api.Family.Infrastructure.Grpc";
package family;

service FamilyService {
  rpc RegisterFamilyGroup (RegisterFamilyGroupRequest) returns (RegisterFamilyGroupResponse);
}

message FamilyMember {
  string profile_id = 1;
  string relationship_type = 2; // Parent | Student
}

message RegisterFamilyGroupRequest {
  string family_name = 1;
  string observations = 2;
  repeated FamilyMember members = 3;
}

message RegisteredMember {
  string member_id = 1;
  string profile_id = 2;
}

message RegisterFamilyGroupResponse {
  string family_id = 1;
  repeated RegisteredMember members = 2;
}
